Repository Yoast/duplicate-post, pull requests merged in 2020-12, with the labels that each got.

#62 P3-258 Style the copy links in the editors
  duplicate-post.css
  js/src/duplicate-post-edit-script.js
Labels: changelog: non-user-facing

#63 P3-237 P3-234 Add notices
  js/src/duplicate-post-edit-script.js
  src/class-duplicate-post.php
  src/class-permissions-helper.php
  src/class-post-duplicator.php
  src/handlers/class-bulk-handler.php
  src/ui/class-admin-bar.php
  src/ui/class-block-editor.php
  src/ui/class-post-states.php
  src/ui/class-user-interface.php
  src/watchers/class-bulk-actions-watcher.php
  src/watchers/class-copied-post-watcher.php
  src/watchers/class-link-actions-watcher.php
  src/watchers/class-original-post-watcher.php
  src/watchers/class-watchers.php
  tests/class-permissions-helper-test.php
  tests/ui/class-admin-bar-test.php
  tests/ui/class-block-editor-test.php
  tests/watchers/class-bulk-actions-watcher-test.php
  tests/watchers/class-copied-post-watcher-test.php
  tests/watchers/class-link-actions-watcher-test.php
  tests/watchers/class-original-post-watcher-test.php
Labels: changelog: non-user-facing

#67 P3-278 Display status and link to original for Rewrite & Republish copies.
  src/ui/class-post-states.php
  src/ui/class-user-interface.php
  tests/ui/class-post-states-test.php
Labels: changelog: non-user-facing

#64 P3-231 Republish overwriting the original post
  js/src/duplicate-post-edit-script.js
  package.json
  src/class-duplicate-post.php
  src/class-post-duplicator.php
  src/class-post-republisher.php
  src/class-utils.php
  src/ui/class-block-editor.php
  src/watchers/class-republished-post-watcher.php
  src/watchers/class-watchers.php
  tests/class-post-republisher-test.php
  tests/class-utils-test.php
  tests/watchers/class-republished-post-watcher-test.php
Labels: changelog: non-user-facing

#70 P3-284 Introduce grunt artifact task
  Gruntfile.js
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/clean.js
  config/grunt/task-config/copy.js
  config/grunt/task-config/shell.js
  config/webpack/webpack.config.js
Labels: changelog: non-user-facing

#65 P3-233 Change Republish Copies
  .travis.yml
  config/webpack/paths.js
  js/src/duplicate-post-strings.js
  readme.txt
  src/ui/class-block-editor.php
  src/ui/class-post-submitbox.php
  tests/ui/class-post-submitbox-test.php
Labels: changelog: non-user-facing

#68 Refactor and update Duplicate Post options
  config/webpack/paths.js
  duplicate-post-admin.php
  duplicate-post-options.php
  duplicate-post.php
  js/src/duplicate-post-edit-script.js
  js/src/duplicate-post-options.js
  src/admin/class-options-form-generator.php
  src/admin/class-options-inputs.php
  src/admin/class-options-page.php
  src/admin/class-options.php
  src/admin/views/options.php
  src/class-utils.php
  src/ui/class-admin-bar.php
  src/ui/class-block-editor.php
  src/ui/class-bulk-actions.php
  src/ui/class-post-submitbox.php
  src/ui/class-row-actions.php
  src/ui/class-user-interface.php
  tests/admin/class-options-form-generator-test.php
  tests/admin/class-options-inputs-test.php
  tests/admin/class-options-page-test.php
  tests/admin/class-options-test.php
  tests/bootstrap.php
  tests/class-permissions-helper-test.php
  tests/class-testcase.php
  tests/ui/class-admin-bar-test.php
  tests/ui/class-bulk-actions-test.php
  tests/ui/class-post-submitbox-test.php
  tests/ui/class-row-actions-test.php
Labels: UI change, changelog: enhancement

#72 P3-280 Handle the cases when a copy is saved as draft, pending, private, etc.
  js/src/duplicate-post-edit-script.js
  src/class-permissions-helper.php
  src/class-post-republisher.php
  tests/class-permissions-helper-test.php
  tests/class-post-republisher-test.php
Labels: changelog: non-user-facing

#71 P3-273 Changes overview page
  config/webpack/paths.js
  css/duplicate-post-options.css
  css/duplicate-post.css
  duplicate-post-options.php
  js/src/duplicate-post-edit-script.js
  js/src/duplicate-post-quick-edit-script.js
  js/src/duplicate-post-strings.js
  src/admin/class-options-page.php
  src/class-utils.php
  src/handlers/class-bulk-handler.php
  src/handlers/class-check-changes-handler.php
  src/handlers/class-handler.php
  src/handlers/class-link-handler.php
  src/handlers/class-save-post-handler.php
  src/ui/class-admin-bar.php
  src/ui/class-asset-manager.php
  src/ui/class-block-editor.php
  src/ui/class-column.php
  src/ui/class-link-builder.php
  src/ui/class-metabox.php
  src/ui/class-post-states.php
  src/ui/class-post-submitbox.php
  src/ui/class-user-interface.php
  tests/admin/class-options-page-test.php
  tests/class-permissions-helper-test.php
  tests/class-utils-test.php
  tests/handlers/class-check-changes-handler-test.php
  tests/ui/class-admin-bar-test.php
  tests/ui/class-asset-manager-test.php
  tests/ui/class-block-editor-test.php
  tests/ui/class-column-test.php
  tests/ui/class-link-builder-test.php
  tests/ui/class-post-states-test.php
  tests/ui/class-post-submitbox-test.php
  tests/watchers/class-bulk-actions-watcher-test.php
  tests/watchers/class-copied-post-watcher-test.php
  tests/watchers/class-link-actions-watcher-test.php
  tests/watchers/class-original-post-watcher-test.php
Labels: changelog: non-user-facing

#75 P3-286 Prevent multiple R&R copies and clean up original when the copy is deleted
  src/class-permissions-helper.php
  src/class-post-republisher.php
  src/handlers/class-bulk-handler.php
  src/handlers/class-link-handler.php
  src/ui/class-admin-bar.php
  src/ui/class-block-editor.php
  src/ui/class-post-submitbox.php
  src/ui/class-row-actions.php
  src/watchers/class-copied-post-watcher.php
  tests/class-permissions-helper-test.php
  tests/class-post-republisher-test.php
  tests/ui/class-admin-bar-test.php
  tests/ui/class-block-editor-test.php
  tests/ui/class-post-submitbox-test.php
  tests/ui/class-row-actions-test.php
  tests/watchers/class-copied-post-watcher-test.php
Labels: changelog: non-user-facing

#74 Add scheduled republishing
  src/class-permissions-helper.php
  src/class-post-republisher.php
  src/class-utils.php
  tests/class-post-republisher-test.php
Labels: changelog: enhancement

#77 P3-281 Remove slug editing from Rewrite & Republish copies
  js/src/duplicate-post-edit-script.js
  src/class-post-duplicator.php
  src/ui/class-classic-editor.php
  src/ui/class-user-interface.php
  tests/ui/class-classic-editor-test.php
Labels: changelog: non-user-facing

#76 P3-288 migrate revisions
  src/class-duplicate-post.php
  src/class-post-republisher.php
  src/class-revisions-migrator.php
  tests/class-post-republisher-test.php
  tests/class-revisions-migrator-test.php
Labels: changelog: non-user-facing

#73 Make the admin bar menu look and behave better
  css/duplicate-post.css
  src/ui/class-admin-bar.php
  tests/ui/class-admin-bar-test.php
Labels: changelog: non-user-facing

#79 P3-263 update R&R link in block editor
  js/src/duplicate-post-edit-script.js
  src/ui/class-block-editor.php
  tests/ui/class-block-editor-test.php
Labels: changelog: non-user-facing

#78 Change link in block editor
  js/src/duplicate-post-edit-script.js
  js/src/duplicate-post-functions.js
  js/src/duplicate-post-strings.js
  src/ui/class-classic-editor.php
Labels: changelog: non-user-facing

#80 P3-294 Remove unused code
  duplicate-post-admin.php
  duplicate-post-common.php
  readme.txt
  src/admin/class-options-form-generator.php
  src/admin/class-options-inputs.php
  src/admin/class-options.php
  src/admin/views/options.php
  src/class-permissions-helper.php
  src/class-post-republisher.php
  src/class-utils.php
  src/handlers/class-link-handler.php
  src/ui/class-metabox.php
  src/ui/class-post-states.php
  src/ui/class-row-actions.php
  src/watchers/class-bulk-actions-watcher.php
  src/watchers/class-copied-post-watcher.php
  src/watchers/class-link-actions-watcher.php
  src/watchers/class-original-post-watcher.php
  src/watchers/class-republished-post-watcher.php
Labels: changelog: non-user-facing

#82 P3-295 Include edit screen option for block editor
  js/src/duplicate-post-edit-script.js
  src/ui/class-block-editor.php
  tests/ui/class-block-editor-test.php
Labels: changelog: non-user-facing

#83 Fix copy task configuration to include CSS folder, and remove moved files from the root
  config/grunt/task-config/copy.js
Labels: changelog: non-user-facing

#81 Remove the unsaved changes warning before redirect that happens due t…
  js/src/duplicate-post-edit-script.js
  js/src/duplicate-post-functions.js
Labels: changelog: non-user-facing
