Repository Yoast/duplicate-post, pull requests merged in 2021-12, with the labels that each got.

#216 Composer: update installer package
  composer.json
Labels: changelog: other, yoast cs/qa

#217 CS: various minor cleanup
  src/ui/newsletter.php
  tests/post-republisher-test.php
  tests/ui/classic-editor-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#218 DUPP-33 Fix scheduled republish bug
  src/post-republisher.php
  tests/post-republisher-test.php
Labels: changelog: bugfix

#219 DUPP-176 Prevent rendering of the script when the store is not available
  js/src/duplicate-post-edit-script.js
  src/ui/block-editor.php
  tests/ui/block-editor-test.php
Labels: changelog: bugfix

#221 Dupp 177 welcome notice
  admin-functions.php
  src/ui/newsletter.php
Labels: changelog: enhancement

#224 Composer: allow plugins
  composer.json
Labels: changelog: non-user-facing, yoast cs/qa
