Repository Yoast/duplicate-post, pull requests merged in 2021-01, with the labels that each got.

#84 P3-298 Fix "Publish on" strings
  js/src/duplicate-post-strings.js
  src/ui/class-asset-manager.php
  src/ui/class-classic-editor.php
  tests/ui/class-asset-manager-test.php
  tests/ui/class-classic-editor-test.php
Labels: changelog: non-user-facing

#85 Ensure Rewrite & Republish bulk action isn't available for trashed posts
  src/ui/class-bulk-actions.php
Labels: changelog: bugfix

#86 P3-302 Disable duplicate focus keyphrase assessment on Rewrite and Republish original post
  src/ui/class-block-editor.php
  tests/ui/class-block-editor-test.php
Labels: changelog: non-user-facing

#87 Ensure R&R doesn't show up in the bulk actions in the drafts posts list.
  src/ui/class-bulk-actions.php
Labels: changelog: bugfix

#88 [QAK-2570] Extend warning text to include rewrite and republish
  src/admin/views/options.php
Labels: changelog: non-user-facing

#89 P3-310 disable Rewrite & Republish when Elementor is active
  src/class-permissions-helper.php
  src/ui/class-block-editor.php
  src/ui/class-bulk-actions.php
  src/ui/class-post-list.php
  src/ui/class-user-interface.php
  tests/class-permissions-helper-test.php
  tests/ui/class-block-editor-test.php
  tests/ui/class-bulk-actions-test.php
Labels: changelog: non-user-facing

#90 Optimized the query and fixed post count
  src/ui/class-post-list.php
Labels: changelog: non-user-facing

#91 Fix fatal errors when `get_current_screen` is not available
  src/ui/class-post-list.php
Labels: changelog: non-user-facing

#93 Update upgrade notice for version 4.0
  duplicate-post-admin.php
Labels: changelog: non-user-facing

#92 P3-299 Disable for WooCommerce products
  src/admin/class-options-form-generator.php
  src/class-permissions-helper.php
  src/class-utils.php
  tests/admin/class-options-form-generator-test.php
Labels: changelog: other

#94 Patch typehinting fatal error
  config/grunt/task-config/copy.js
  duplicate-post-admin.php
  src/class-post-republisher.php
  src/handlers/class-bulk-handler.php
  src/ui/class-classic-editor.php
  src/ui/class-post-list.php
  src/ui/class-post-states.php
  src/ui/class-row-actions.php
Labels: changelog: bugfix

#95 Enforce missing checks
  src/ui/class-admin-bar.php
  src/ui/class-block-editor.php
  src/ui/class-classic-editor.php
  src/ui/class-column.php
  src/ui/class-link-builder.php
  src/ui/class-metabox.php
  src/ui/class-post-list.php
  src/ui/class-post-states.php
  src/ui/class-row-actions.php
  src/watchers/class-bulk-actions-watcher.php
  src/watchers/class-copied-post-watcher.php
  src/watchers/class-link-actions-watcher.php
  src/watchers/class-original-post-watcher.php
  src/watchers/class-republished-post-watcher.php
Labels: changelog: bugfix

#97 Fix typos and improve link text
  readme.txt
Labels: changelog: non-user-facing, community-patch

#98 P3-324 Add editorconfig file
  .editorconfig
  .gitattributes
Labels: changelog: non-user-facing

#100 P3-307 Add improved Elementor compatibility
  config/webpack/paths.js
  js/src/duplicate-post-elementor.js
  src/class-permissions-helper.php
  src/class-post-republisher.php
  src/ui/class-asset-manager.php
  src/ui/class-block-editor.php
  src/ui/class-bulk-actions.php
  src/ui/class-post-list.php
  src/ui/class-user-interface.php
  tests/class-permissions-helper-test.php
  tests/class-post-republisher-test.php
  tests/ui/class-block-editor-test.php
  tests/ui/class-bulk-actions-test.php
Labels: changelog: enhancement

#101 P3-308 Prevent the original post from being listed in the link suggestions
  src/ui/class-block-editor.php
  tests/ui/class-block-editor-test.php
Labels: changelog: bugfix

#96 Prevent accidental deletion of copy when it's not been republished yet
  src/class-post-duplicator.php
  src/class-post-republisher.php
  src/class-utils.php
Labels: changelog: non-user-facing

#103 P3-336 Prevent copying of R&R related meta fields when creating regular copies
  duplicate-post-admin.php
Labels: changelog: bugfix

#104 P3-337 Hide the post status changer in Elementor instead of removing it
  src/ui/class-block-editor.php
  tests/ui/class-block-editor-test.php
Labels: changelog: non-user-facing
