Repository Yoast/duplicate-post, pull requests merged in 2021-03, with the labels that each got.

#115 P3-434 Fix R&R comparison screen in WP 5.7
  src/handlers/class-check-changes-handler.php
Labels: changelog: bugfix

#116 P3-321 improve Metabox class
  src/ui/class-metabox.php
  tests/ui/class-metabox-test.php
Labels: changelog: non-user-facing

#118 CS: use short arrays
  compat/duplicate-post-wpml.php
  duplicate-post-admin.php
  duplicate-post-common.php
  duplicate-post.php
  src/handlers/class-check-changes-handler.php
  src/ui/class-bulk-actions.php
Labels: changelog: non-user-facing, yoast cs/qa

#119 QA: no leading backslash for import use statements
  tests/class-utils-test.php
  tests/ui/class-asset-manager-test.php
  tests/ui/class-link-builder-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#121 QA: declare static closures as static
  src/admin/class-options.php
  src/ui/class-block-editor.php
  tests/admin/class-options-form-generator-test.php
  tests/class-post-duplicator-test.php
  tests/class-testcase.php
  tests/ui/class-block-editor-test.php
  tests/ui/class-classic-editor-test.php
  tests/ui/class-link-builder-test.php
  tests/ui/class-row-actions-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#122 Modernize: use __DIR__ instead of dirname( __FILE__ )
  duplicate-post-admin.php
  duplicate-post.php
Labels: changelog: non-user-facing, yoast cs/qa

#123 CS: don't use Yoda conditions
  compat/duplicate-post-gutenberg.php
  duplicate-post-admin.php
  duplicate-post-common.php
  src/class-post-duplicator.php
  src/handlers/class-check-changes-handler.php
  src/handlers/class-link-handler.php
  src/ui/class-column.php
  src/ui/class-link-builder.php
Labels: changelog: non-user-facing, yoast cs/qa

#124 CS: various whitespace fixes
  src/admin/class-options-page.php
  src/class-revisions-migrator.php
  tests/admin/class-options-page-test.php
  tests/class-revisions-migrator-test.php
  tests/handlers/class-check-changes-handler-test.php
  tests/ui/class-block-editor-test.php
  tests/ui/class-row-actions-test.php
  tests/watchers/class-bulk-actions-watcher-test.php
  tests/watchers/class-copied-post-watcher-test.php
  tests/watchers/class-original-post-watcher-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#125 CS: use pre-increment/decrement
  src/class-utils.php
  src/handlers/class-bulk-handler.php
Labels: changelog: non-user-facing, yoast cs/qa

#126 CS: use parentheses around arithmetic operations
  duplicate-post.php
  src/class-revisions-migrator.php
Labels: changelog: non-user-facing, yoast cs/qa

#127 Docs: various minor formatting fixes
  duplicate-post-admin.php
  duplicate-post-common.php
  duplicate-post.php
  src/admin/class-options-form-generator.php
  src/admin/class-options-inputs.php
  src/admin/class-options-page.php
  src/admin/class-options.php
  src/admin/views/options.php
  src/class-post-duplicator.php
  src/class-post-republisher.php
  src/class-utils.php
  src/handlers/class-check-changes-handler.php
  src/ui/class-classic-editor.php
  src/ui/class-link-builder.php
  src/ui/class-metabox.php
  src/ui/class-row-actions.php
  src/watchers/class-bulk-actions-watcher.php
  src/watchers/class-link-actions-watcher.php
  tests/admin/class-options-form-generator-test.php
  tests/watchers/class-copied-post-watcher-test.php
  tests/watchers/class-original-post-watcher-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#128 Docs: remove unsupported `@ignore` tag
  src/admin/class-options-form-generator.php
Labels: changelog: non-user-facing, yoast cs/qa

#129 QA: fix implicit array creation
  tests/ui/class-classic-editor-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#130 CS: order use statements alphabetically
  tests/class-post-republisher-test.php
  tests/handlers/class-check-changes-handler-test.php
  tests/ui/class-row-actions-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#131 CS: else(if) must be on new line
  .phpcs.xml.dist
  compat/duplicate-post-gutenberg.php
  duplicate-post-admin.php
  duplicate-post-common.php
  src/class-post-duplicator.php
  src/class-post-republisher.php
  src/class-utils.php
  src/handlers/class-link-handler.php
  src/ui/class-admin-bar.php
  src/ui/class-link-builder.php
Labels: changelog: non-user-facing, yoast cs/qa

#132 QA: remove a redundant condition block
  src/class-permissions-helper.php
Labels: changelog: non-user-facing, yoast cs/qa

#133 CS: consistent placement of operators
  duplicate-post-admin.php
  src/handlers/class-check-changes-handler.php
  src/handlers/class-link-handler.php
  src/ui/class-row-actions.php
  src/watchers/class-bulk-actions-watcher.php
  src/watchers/class-copied-post-watcher.php
  src/watchers/class-link-actions-watcher.php
  src/watchers/class-original-post-watcher.php
  src/watchers/class-republished-post-watcher.php
Labels: changelog: non-user-facing, yoast cs/qa

#134 QA: remove redundant variable assignment
  duplicate-post-admin.php
Labels: changelog: non-user-facing, yoast cs/qa

#135 QA: remove unused variables
  tests/ui/class-block-editor-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#136 CS: remove redundant file docblocks
  .phpcs.xml.dist
  duplicate-post-options.php
  src/admin/class-options-form-generator.php
  src/admin/class-options-inputs.php
  src/admin/class-options-page.php
  src/admin/class-options.php
  src/class-duplicate-post.php
  src/class-permissions-helper.php
  src/class-post-duplicator.php
  src/class-post-republisher.php
  src/class-revisions-migrator.php
  src/class-utils.php
  src/handlers/class-bulk-handler.php
  src/handlers/class-check-changes-handler.php
  src/handlers/class-handler.php
  src/handlers/class-link-handler.php
  src/handlers/class-save-post-handler.php
  src/ui/class-admin-bar.php
  src/ui/class-asset-manager.php
  src/ui/class-block-editor.php
  src/ui/class-bulk-actions.php
  src/ui/class-classic-editor.php
  src/ui/class-column.php
  src/ui/class-link-builder.php
  src/ui/class-metabox.php
  src/ui/class-post-states.php
  src/ui/class-row-actions.php
  src/ui/class-user-interface.php
  src/watchers/class-bulk-actions-watcher.php
  src/watchers/class-copied-post-watcher.php
  src/watchers/class-link-actions-watcher.php
  src/watchers/class-original-post-watcher.php
  src/watchers/class-republished-post-watcher.php
  src/watchers/class-watchers.php
  tests/admin/class-options-form-generator-test.php
  tests/admin/class-options-inputs-test.php
  tests/admin/class-options-page-test.php
  tests/admin/class-options-test.php
  tests/class-permissions-helper-test.php
  tests/class-post-duplicator-test.php
  tests/class-post-republisher-test.php
  tests/class-revisions-migrator-test.php
  tests/class-testcase.php
  tests/class-utils-test.php
  tests/handlers/class-check-changes-handler-test.php
  tests/ui/class-admin-bar-test.php
  tests/ui/class-asset-manager-test.php
  tests/ui/class-block-editor-test.php
  tests/ui/class-bulk-actions-test.php
  tests/ui/class-classic-editor-test.php
  tests/ui/class-column-test.php
  tests/ui/class-link-builder-test.php
  tests/ui/class-metabox-test.php
  tests/ui/class-post-states-test.php
  tests/ui/class-row-actions-test.php
  tests/watchers/class-bulk-actions-watcher-test.php
  tests/watchers/class-copied-post-watcher-test.php
  tests/watchers/class-link-actions-watcher-test.php
  tests/watchers/class-original-post-watcher-test.php
  tests/watchers/class-republished-post-watcher-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#137 Docs: fix up the remaining `@package` tags
  compat/duplicate-post-gutenberg.php
  compat/duplicate-post-jetpack.php
  compat/duplicate-post-wpml.php
  duplicate-post-admin.php
  duplicate-post-common.php
  duplicate-post.php
  tests/bootstrap.php
Labels: changelog: non-user-facing, yoast cs/qa

#138 QA: consistently use `use` statements for classes
  src/admin/class-options-form-generator.php
  src/class-permissions-helper.php
  src/class-post-duplicator.php
  src/class-post-republisher.php
  src/class-utils.php
  src/handlers/class-check-changes-handler.php
  src/ui/class-classic-editor.php
  src/ui/class-link-builder.php
  src/ui/class-metabox.php
  src/ui/class-post-states.php
  src/ui/class-row-actions.php
  src/watchers/class-copied-post-watcher.php
  src/watchers/class-original-post-watcher.php
  tests/admin/class-options-form-generator-test.php
  tests/class-permissions-helper-test.php
  tests/class-post-duplicator-test.php
  tests/class-post-republisher-test.php
  tests/class-revisions-migrator-test.php
  tests/handlers/class-check-changes-handler-test.php
  tests/ui/class-admin-bar-test.php
  tests/ui/class-block-editor-test.php
  tests/ui/class-bulk-actions-test.php
  tests/ui/class-classic-editor-test.php
  tests/ui/class-link-builder-test.php
  tests/ui/class-metabox-test.php
  tests/ui/class-post-states-test.php
  tests/ui/class-row-actions-test.php
  tests/watchers/class-bulk-actions-watcher-test.php
  tests/watchers/class-copied-post-watcher-test.php
  tests/watchers/class-link-actions-watcher-test.php
  tests/watchers/class-original-post-watcher-test.php
  tests/watchers/class-republished-post-watcher-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#139 QA: call global functions using a fully qualified name
  duplicate-post-options.php
  src/admin/class-options-form-generator.php
  src/admin/class-options.php
  src/class-post-republisher.php
  src/handlers/class-check-changes-handler.php
  src/handlers/class-link-handler.php
  src/ui/class-bulk-actions.php
  src/watchers/class-link-actions-watcher.php
  tests/admin/class-options-page-test.php
  tests/admin/class-options-test.php
  tests/class-post-republisher-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#140 QA: use global constants with a fully qualified name
  src/admin/class-options-page.php
  src/class-post-republisher.php
  src/handlers/class-check-changes-handler.php
  src/handlers/class-save-post-handler.php
  src/ui/class-asset-manager.php
  tests/ui/class-asset-manager-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#117 Remove composer.lock file
  .gitignore
  composer.lock
Labels: changelog: non-user-facing, yoast cs/qa

#141 Composer: set minimum supported PHP version in `require`
  composer.json
Labels: changelog: non-user-facing, yoast cs/qa

#142 Travis/Composer: switch over to parallel linting of PHP files
  .travis.yml
  composer.json
Labels: changelog: non-user-facing, yoast cs/qa

#120 CS: use brackets around condition
  src/admin/class-options-inputs.php
  src/class-post-duplicator.php
  src/ui/class-block-editor.php
  src/ui/class-column.php
Labels: changelog: non-user-facing, yoast cs/qa

#143 Travis: various minor tweaks
  .travis.yml
Labels: changelog: non-user-facing, yoast cs/qa

#144 Composer/Travis: remove sniffing against VIPCS
  .travis.yml
  composer.json
Labels: changelog: non-user-facing, yoast cs/qa

#145 CS: remove a few more redundant @ignore comments
  duplicate-post-admin.php
  duplicate-post.php
Labels: changelog: non-user-facing, yoast cs/qa

#146 QA: no FQN function calls in non-namespaced file
  duplicate-post-admin.php
  tests/bootstrap.php
Labels: changelog: non-user-facing, yoast cs/qa

#150 QA: improve output escaping [1]
  duplicate-post-admin.php
Labels: changelog: non-user-facing, yoast cs/qa

#151 QA: improve output escaping [2]
  duplicate-post-common.php
Labels: changelog: non-user-facing, yoast cs/qa

#153 QA: remove double output escaping
  src/admin/class-options-form-generator.php
Labels: changelog: non-user-facing, yoast cs/qa

#147 CS: consistency for file includes
  duplicate-post-admin.php
  duplicate-post.php
Labels: changelog: non-user-facing, yoast cs/qa

#149 QA: add missing namespace
  src/admin/views/options.php
Labels: changelog: non-user-facing, yoast cs/qa

#152 QA: improve output escaping [3]
  src/class-utils.php
Labels: changelog: non-user-facing, yoast cs/qa

#154 CS: minor clean up after merges
  src/ui/class-column.php
Labels: changelog: non-user-facing, yoast cs/qa

#155 QA: remove the `duplicate_post_classic_editor_clone_link()` function
  compat/duplicate-post-gutenberg.php
Labels: changelog: non-user-facing, yoast cs/qa

#157 PHPCS: Switch over to using YoastCS
  .phpcs.xml.dist
  admin-functions.php
  compat/wpml-functions.php
  composer.json
  duplicate-post.php
  src/admin/options-page.php
  src/handlers/check-changes-handler.php
  src/handlers/link-handler.php
  src/handlers/save-post-handler.php
  src/post-republisher.php
  src/ui/bulk-actions.php
  src/ui/classic-editor.php
  src/watchers/bulk-actions-watcher.php
  src/watchers/link-actions-watcher.php
  src/watchers/republished-post-watcher.php
  tests/bootstrap.php
  tests/post-republisher-test.php
  tests/ui/admin-bar-test.php
  tests/ui/classic-editor-test.php
  tests/watchers/republished-post-watcher-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#158 Travis: only lint against high/low PHP and run tests on more PHP versions
  .travis.yml
Labels: changelog: non-user-facing, yoast cs/qa

#159 QA: clean up global variables set in tests
  tests/handlers/check-changes-handler-test.php
  tests/post-republisher-test.php
  tests/ui/admin-bar-test.php
  tests/ui/classic-editor-test.php
  tests/watchers/bulk-actions-watcher-test.php
  tests/watchers/link-actions-watcher-test.php
  tests/watchers/republished-post-watcher-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#160 QA: Unit tests: use the correct parameter order
  tests/ui/classic-editor-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#161 QA: use strict PHPUnit assertions
  tests/admin/options-form-generator-test.php
  tests/admin/options-inputs-test.php
  tests/admin/options-test.php
  tests/permissions-helper-test.php
  tests/post-duplicator-test.php
  tests/post-republisher-test.php
  tests/ui/bulk-actions-test.php
  tests/ui/classic-editor-test.php
  tests/ui/column-test.php
  tests/ui/link-builder-test.php
  tests/utils-test.php
  tests/watchers/bulk-actions-watcher-test.php
  tests/watchers/link-actions-watcher-test.php
  tests/watchers/republished-post-watcher-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#164 QA: remove duplicate code
  admin-functions.php
Labels: changelog: non-user-facing, yoast cs/qa

#165 Tests: fix broken setup of mocked WP_Role objects + fix an incorrect test
  tests/admin/options-form-generator-test.php
  tests/testcase.php
Labels: changelog: non-user-facing, yoast cs/qa
