Repository Yoast/duplicate-post, pull requests merged in 2021-05, with the labels that each got.

#173 Fix bug in test
  tests/admin/options-page-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#172 QA: rename test
  tests/admin/options-page-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#174 CS/QA: rename function parameters
  src/ui/asset-manager.php
  src/ui/classic-editor.php
  tests/ui/block-editor-test.php
  tests/ui/link-builder-test.php
Labels: changelog: other, yoast cs/qa

#178 Push to yoast-dist on travis task
  .travis.yml
  config/travis/deploy_keys/id_rsa_yoast_dist.enc
  config/travis/deploy_to_dist.sh
Labels: changelog: non-user-facing

#179 add wordpress plugin part to composer.json
  composer.json
Labels: changelog: non-user-facing

#180 Composer wp plugin
  composer.json
Labels: changelog: non-user-facing

#183 Fix composer initialize on master
  duplicate-post.php
Labels: changelog: bugfix
