Repository Yoast/duplicate-post, pull requests merged in 2022-11, with the labels that each got.

#270 GH Actions: various tweaks
  .github/workflows/cs.yml
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: changelog: non-user-facing, yoast cs/qa

#272 Update changelog format (both in file and creation settings)
  config/grunt/task-config/update-changelog-to-latest.js
  readme.txt
Labels: changelog: non-user-facing

#273 Composer: update test utilities
  composer.json
Labels: changelog: non-user-facing, yoast cs/qa

#274 Tests: fix PHP 8.2 compatibility
  tests/admin/options-form-generator-test.php
  tests/bootstrap.php
  tests/testcase.php
  tests/ui/admin-bar-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#276 GH Actions: run the tests against PHP 8.2
  .github/workflows/test.yml
Labels: changelog: other, yoast cs/qa

#278 Do fix worpdress org format
  config/grunt/task-config/update-changelog-to-latest.js
  readme.txt
Labels: changelog: non-user-facing
