Repository Yoast/duplicate-post, pull requests merged in 2022-06, with the labels that each got.

#251 Add grunt tasks for automation
  .gitignore
  Gruntfile.js
  config/grunt/custom-tasks/check-deploy-allowed.js
  config/grunt/custom-tasks/sync-readme-stable-tag.js
  config/grunt/lib/wordpress-api.js
  config/grunt/task-config/update-changelog-to-latest.js
  package.json
  readme.txt
Labels: changelog: non-user-facing

#254 DUPP-572 Apply core class to get margins right
  src/ui/classic-editor.php
Labels: changelog: bugfix

#255 DUPP-52 improve gettext usage
  src/ui/classic-editor.php
  tests/ui/classic-editor-test.php
Labels: changelog: enhancement
