Repository Yoast/duplicate-post, pull requests merged in 2022-01, with the labels that each got.

#226 CI: switch to GitHub Actions
  .gitattributes
  .github/workflows/cs.yml
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .travis.yml
  composer.json
  config/travis/deploy_keys/id_rsa_yoast_dist.enc
  config/travis/deploy_to_dist.sh
Labels: changelog: non-user-facing, yoast cs/qa

#227 GH Actions: fix the deploy fail
  .github/workflows/deploy.yml
Labels: changelog: non-user-facing, yoast cs/qa

#228 Sets the WordPress tested up to version to 5.9.
  readme.txt
Labels: changelog: other

#229 DUPP-217 Fix welcome notice
  admin-functions.php
  src/admin/options.php
  src/admin/views/options.php
  src/ui/newsletter.php
Labels: changelog: non-user-facing, UI change

#230 DUPP-218 Always hide welcome notice to upgrading users
  admin-functions.php
Labels: changelog: non-user-facing
