Repository Yoast/duplicate-post, pull requests merged in 2023-12, with the labels that each got.

#346 "Do not copy these fields" is not working properly.
  admin-functions.php
Labels: changelog: bugfix, community-patch

#348 Composer: implement CS menu and extra commands
  .github/workflows/cs.yml
  .github/workflows/lint.yml
  composer.json
  config/composer/actions.php
Labels: changelog: non-user-facing, yoast cs/qa

#349 CS: minor tweaks to comply with YoastCS 3.0
  src/ui/newsletter.php
  tests/Unit/Admin/Options_Form_Generator_Test.php
  tests/Unit/Admin/Options_Inputs_Test.php
  tests/WP/Post_Duplicator_Test.php
  tests/WP/bootstrap.php
Labels: changelog: non-user-facing, yoast cs/qa

#350 CS/QA: use `printf()`, not `echo sprintf()`
  src/handlers/check-changes-handler.php
  src/ui/column.php
Labels: changelog: non-user-facing, yoast cs/qa

#351 CS/QA: use import `use` statements
  admin-functions.php
Labels: changelog: non-user-facing, yoast cs/qa

#352 Tests: make all classes either abstract or final
  tests/Unit/Admin/Options_Form_Generator_Test.php
  tests/Unit/Admin/Options_Inputs_Test.php
  tests/Unit/Admin/Options_Page_Test.php
  tests/Unit/Admin/Options_Test.php
  tests/Unit/Handlers/Check_Changes_Handler_Test.php
  tests/Unit/Permissions_Helper_Test.php
  tests/Unit/Post_Duplicator_Test.php
  tests/Unit/Post_Republisher_Test.php
  tests/Unit/Revisions_Migrator_Test.php
  tests/Unit/UI/Admin_Bar_Test.php
  tests/Unit/UI/Asset_Manager_Test.php
  tests/Unit/UI/Block_Editor_Test.php
  tests/Unit/UI/Bulk_Actions_Test.php
  tests/Unit/UI/Classic_Editor_Test.php
  tests/Unit/UI/Column_Test.php
  tests/Unit/UI/Link_Builder_Test.php
  tests/Unit/UI/Metabox_Test.php
  tests/Unit/UI/Post_States_Test.php
  tests/Unit/UI/Row_Actions_Test.php
  tests/Unit/Utils_Test.php
  tests/Unit/Watchers/Bulk_Actions_Watcher_Test.php
  tests/Unit/Watchers/Copied_Post_Watcher_Test.php
  tests/Unit/Watchers/Link_Actions_Watcher_Test.php
  tests/Unit/Watchers/Original_Post_Watcher_Test.php
  tests/Unit/Watchers/Republished_Post_Watcher_Test.php
  tests/WP/Post_Duplicator_Test.php
Labels: changelog: non-user-facing, yoast cs/qa

#353 Docs: various updates
  admin-functions.php
  common-functions.php
  compat/jetpack-functions.php
  compat/wpml-functions.php
  duplicate-post.php
  src/admin/options-form-generator.php
  src/post-duplicator.php
  src/ui/block-editor.php
  src/ui/newsletter.php
  src/utils.php
  tests/Unit/Admin/Options_Form_Generator_Test.php
  tests/Unit/Admin/Options_Inputs_Test.php
  tests/Unit/Admin/Options_Page_Test.php
  tests/Unit/Admin/Options_Test.php
  tests/Unit/Handlers/Check_Changes_Handler_Test.php
  tests/Unit/Permissions_Helper_Test.php
  tests/Unit/Post_Duplicator_Test.php
  tests/Unit/Post_Republisher_Test.php
  tests/Unit/Revisions_Migrator_Test.php
  tests/Unit/UI/Admin_Bar_Test.php
  tests/Unit/UI/Asset_Manager_Test.php
  tests/Unit/UI/Block_Editor_Test.php
  tests/Unit/UI/Bulk_Actions_Test.php
  tests/Unit/UI/Classic_Editor_Test.php
  tests/Unit/UI/Column_Test.php
  tests/Unit/UI/Link_Builder_Test.php
  tests/Unit/UI/Metabox_Test.php
  tests/Unit/UI/Post_States_Test.php
  tests/Unit/UI/Row_Actions_Test.php
  tests/Unit/Utils_Test.php
  tests/Unit/Watchers/Bulk_Actions_Watcher_Test.php
  tests/Unit/Watchers/Copied_Post_Watcher_Test.php
  tests/Unit/Watchers/Link_Actions_Watcher_Test.php
  tests/Unit/Watchers/Original_Post_Watcher_Test.php
  tests/Unit/Watchers/Republished_Post_Watcher_Test.php
  tests/WP/Post_Duplicator_Test.php
Labels: changelog: non-user-facing, yoast cs/qa

#354 CS/QA: use WP alternative for some native PHP functions
  admin-functions.php
Labels: changelog: non-user-facing, yoast cs/qa

#355 Composer/PHPCS: update to YoastCS 3.0.0
  .github/workflows/cs.yml
  .phpcs.xml.dist
  composer.json
Labels: changelog: non-user-facing, yoast cs/qa

#347 Sets the minimum supported WordPress version to 6.3.
  duplicate-post.php
  readme.txt
Labels: changelog: other
