Repository Yoast/duplicate-post, pull requests merged in 2023-11, with the labels that each got.

#332 Set the WordPress tested up to version to 6.4
  readme.txt
Labels: changelog: other

#334 Tests: use PSR-4
  .phpcs.xml.dist
  composer.json
  phpunit-wp.xml.dist
  phpunit.xml.dist
  tests/Unit/Admin/Options_Form_Generator_Test.php
  tests/Unit/Admin/Options_Inputs_Test.php
  tests/Unit/Admin/Options_Page_Test.php
  tests/Unit/Admin/Options_Test.php
  tests/Unit/Handlers/Check_Changes_Handler_Test.php
  tests/Unit/Permissions_Helper_Test.php
  tests/Unit/Post_Duplicator_Test.php
  tests/Unit/Post_Republisher_Test.php
  tests/Unit/Revisions_Migrator_Test.php
  tests/Unit/TestCase.php
  tests/Unit/UI/Admin_Bar_Test.php
  tests/Unit/UI/Asset_Manager_Test.php
  tests/Unit/UI/Block_Editor_Test.php
  tests/Unit/UI/Bulk_Actions_Test.php
  tests/Unit/UI/Classic_Editor_Test.php
  tests/Unit/UI/Column_Test.php
  tests/Unit/UI/Link_Builder_Test.php
  tests/Unit/UI/Metabox_Test.php
  tests/Unit/UI/Post_States_Test.php
  tests/Unit/UI/Row_Actions_Test.php
  tests/Unit/Utils_Test.php
  tests/Unit/Watchers/Bulk_Actions_Watcher_Test.php
  tests/Unit/Watchers/Copied_Post_Watcher_Test.php
  tests/Unit/Watchers/Link_Actions_Watcher_Test.php
  tests/Unit/Watchers/Original_Post_Watcher_Test.php
  tests/Unit/Watchers/Republished_Post_Watcher_Test.php
  tests/Unit/bootstrap.php
  tests/WP/Post_Duplicator_Test.php
  tests/WP/bootstrap.php
  tests/unit/bootstrap.php
Labels: changelog: non-user-facing, yoast cs/qa

#335 GH Actions: enable linting and testing against PHP 8.3
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: changelog: other, yoast cs/qa

#336 Tests: make dataproviders `static`
  tests/Unit/Admin/Options_Form_Generator_Test.php
  tests/Unit/Permissions_Helper_Test.php
  tests/Unit/Post_Duplicator_Test.php
  tests/Unit/Post_Republisher_Test.php
  tests/Unit/UI/Block_Editor_Test.php
  tests/Unit/Utils_Test.php
Labels: changelog: non-user-facing, yoast cs/qa

#338 Composer.json: add link to security policy
  composer.json
Labels: changelog: other, yoast cs/qa

#339 GH Actions: switch to Coveralls action runner to upload reports
  .github/workflows/test.yml
Labels: changelog: non-user-facing, yoast cs/qa

#340 GH Actions: update a few links in inline comments
  .github/workflows/cs.yml
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: changelog: non-user-facing, yoast cs/qa

#337 Various small bug fixes
  admin-functions.php
  src/ui/column.php
  src/ui/newsletter.php
Labels: changelog: non-user-facing, yoast cs/qa
