Repository Yoast/duplicate-post, pull requests merged in 2024-07, with the labels that each got.

#372 Sets the WordPress tested up to version to 6.6
  readme.txt
Labels: changelog: other

#375 fix developer guide link
  README.md
Labels: changelog: non-user-facing

#374 fix post excerpt typo
  admin-functions.php
Labels: changelog: bugfix
