Repository Yoast/duplicate-post, pull requests merged in 2024-03, with the labels that each got.

#363 Sets the WordPress tested up to version to 6.5
  readme.txt
Labels: changelog: other

#364 Fix notices errors with some locales
  composer.json
  js/src/duplicate-post-edit-script.js
  src/watchers/copied-post-watcher.php
  src/watchers/link-actions-watcher.php
  src/watchers/original-post-watcher.php
  src/watchers/republished-post-watcher.php
  tests/Unit/Watchers/Copied_Post_Watcher_Test.php
  tests/Unit/Watchers/Link_Actions_Watcher_Test.php
  tests/Unit/Watchers/Original_Post_Watcher_Test.php
  tests/Unit/Watchers/Republished_Post_Watcher_Test.php
Labels: changelog: bugfix

#360 Fix Possible NULL Value of `duplicate_post_taxonomies_blacklist`
  admin-functions.php
Labels: community-patch
